// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRb0xV0hWMpkZsQirswrNYxONDtwV2Vfw',
    appId: '1:240284139013:web:dd3cfe185473034083666c',
    messagingSenderId: '240284139013',
    projectId: 'chatai-c8385',
    authDomain: 'chatai-c8385.firebaseapp.com',
    storageBucket: 'chatai-c8385.firebasestorage.app',
    measurementId: 'G-5BEY9KETTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_219STbr_cBo1HjyeuTWyKDseDSUEUPY',
    appId: '1:240284139013:android:e14a3b297ee491c383666c',
    messagingSenderId: '240284139013',
    projectId: 'chatai-c8385',
    storageBucket: 'chatai-c8385.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKVXW5PhHbNqcPqCMHL-A7SDOv6VHZdH0',
    appId: '1:240284139013:ios:6bf56795e422c8ff83666c',
    messagingSenderId: '240284139013',
    projectId: 'chatai-c8385',
    storageBucket: 'chatai-c8385.firebasestorage.app',
    iosBundleId: 'com.chatai.mobile',
  );
}
